### ISSUE TITLE
ETA not displayed since update 0.3.0

### ISSUE THREAD

**Issue by J-Schaefer** [kanocz/octopi_eta_override#17]
Hello,
since the update to version 0.3.0 my printer does not display the ETA correctly and the telegram extension does not send status updates due to an error. The error is in both cases the same. Here is an extract from the log file:
```bash
2022-08-24 15:58:39,575 - octoprint.util.comm - ERROR - Error while processing hook PrusaETAOverride:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4040, in _readline
    ret = hook(self, ret)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrusaETAOverride/__init__.py", line 84, in parse_line
    self._estimator.estimated_time = int(m.group('eta')) * 60
AttributeError: 'NoneType' object has no attribute 'estimated_time'
```
hth

Cheers, Jeroen

**Comment by arekm** [comment]
Please show terminal output from octoprint at printing time. There should be responses like
```
Recv: NORMAL MODE: Percent done: 29; print time remaining in mins: 4; Change in mins: -1
Recv: SILENT MODE: Percent done: 28; print time remaining in mins: 5; Change in mins: -1
```

**Comment by arekm** [comment]
Please try:
https://github.com/arekm/octopi_eta_override/archive/devel.zip
(install from octoprint plugin manager; you can just point to URL there)

**Comment by J-Schaefer** [comment]
That actually helped. Thanks!
